### PR TITLE
Better format the recipe & rerender

### PR DESCRIPTION
**Pull request by mrakitin**
Same version.

### CODE REVIEW

**Comment by mrakitin** [comment]
The latest conda-smithy brought a config on OSX using the compiler stack 7, which we don't have yet. Need to figure out how to disable it for now.

@CJ-Wright, any ideas how to disable "xraylib-feedstock (osx osx_fortran_compiler_version7python3.6)"?

**Comment by CJ-Wright** [comment]
You could force pin the fortran compiler for osx

**Comment by mrakitin** [comment]
Do you have an example?

**Comment by CJ-Wright** [comment]
Not off the top of my head. You could potentially also merge this as is. The failing builds won't upload a package but the others should.

**Comment by mrakitin** [comment]
It must be something coming from https://github.com/conda-forge/conda-forge-pinning-feedstock/blob/298598da8f5c188ee9cfd10ad882a03ea8467b3e/recipe/conda_build_config.yaml#L32.

I have no idea what would be the corresponding parameter in `conda-forge.yml`. Any ideas @CJ-Wright, @mariusvniekerk? Thanks!

**Comment by CJ-Wright** [comment]
you could use a [`conda_forge_config.yaml`](https://conda-forge.readthedocs.io/en/latest/meta.html#build-matrices)

**Comment by mrakitin** [comment]
Thanks @CJ-Wright, that worked! A minor correction: the file name is `conda_build_config.yaml`.

**Pull request merged**
