### PR TITLE
Python 3.9

### PR DESCRIPTION
**Pull request by mrakitin**
This update has OSX / Python 3.8 failure, which is not a blocker for now.

### CODE REVIEW

**Comment by mrakitin** [comment]
@tschoonj , what do you think can be the reason for [that single failure](https://dev.azure.com/nsls2forge/nsls2forge/_build/results?buildId=6867&view=logs&j=3ddc9a6a-6f8e-586b-5fb7-5b816fd04122&t=215f7884-e487-570e-dd69-5b80207188ab) (OSX & Python 3.8)? I do not see that problem in conda-forge's feedstock: https://github.com/conda-forge/xraylib-feedstock/pull/27. I'd appreciate any suggestions, thanks!

**Comment by tschoonj** [comment]
You can fix it by putting:

```bash
if [ $(uname) = Darwin ] ; then
	CFLAGS+=" -Wno-error=deprecated-declarations "
fi
```

to your build.sh

**Comment by mrakitin** [comment]
Awesome! Thanks a lot, @tschoonj :)
I did not look at that critical file, only compared `meta.yaml`. I'll sync the contents of this feedstock with CF.

**Comment by tschoonj** [comment]
Why are you not using the conda-forge build instead?

**Comment by mrakitin** [comment]
We will, it's on our road map.

**Pull request merged**
